version: '3.8'

services:
  app:
    image: my-go-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
